spring:
  profiles:
    active: dev
#    active: formal

  application:
    name: dingitems

  jackson:
    default-property-inclusion: non_null #全局配置返回字段值有null 则不返回
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      # 文件最大限制
      max-file-size: 1024MB
      # 请求最大限制
      max-request-size: 1024MB
      enabled: true
      # 设置文件缓存的临界点,超过则先保存到临时目录,默认为0,所有文件都会进行缓存
      file-size-threshold: 0

http:
  encoding:
    enabled: true
    charset: UTF-8
    force: true
mybatis-plus:
  mapperLocations: classpath*:mapper/*.xml
  type-aliases-package: com.ding.dingitems.*.entity.*
  identity: MYSQL
logging:
  config: classpath:logback-spring.xml
#解决jsp实时更新的问题
server:
  servlet:
    context-path: /
  #    jsp:
#      init-parameters:
#        development: true
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
    url-charset: UTF-8
    max-http-post-size: 500MB
    max-post-size: 500MB




